package com.skill.exchange.dao;

import com.skill.exchange.domain.Skill;
import com.skill.exchange.domain.SkillExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SkillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    long countByExample(SkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    int deleteByExample(SkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    int insert(Skill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    int insertSelective(Skill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    List<Skill> selectByExample(SkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    Skill selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    int updateByExampleSelective(@Param("record") Skill record, @Param("example") SkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    int updateByExample(@Param("record") Skill record, @Param("example") SkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    int updateByPrimaryKeySelective(Skill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    int updateByPrimaryKey(Skill record);

    List<Skill> selectByKeyWord(String keyWord);
}