package com.skill.exchange.domain;

import java.util.Date;

public class Message {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.id
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.content
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.create_time
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.student_id
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    private Integer studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.student_real_name
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    private String studentRealName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.student_num
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    private String studentNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.state
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    private boolean state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.id
     *
     * @return the value of message.id
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.id
     *
     * @param id the value for message.id
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.content
     *
     * @return the value of message.content
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.content
     *
     * @param content the value for message.content
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.create_time
     *
     * @return the value of message.create_time
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.create_time
     *
     * @param createTime the value for message.create_time
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.student_id
     *
     * @return the value of message.student_id
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.student_id
     *
     * @param studentId the value for message.student_id
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.student_real_name
     *
     * @return the value of message.student_real_name
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public String getStudentRealName() {
        return studentRealName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.student_real_name
     *
     * @param studentRealName the value for message.student_real_name
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public void setStudentRealName(String studentRealName) {
        this.studentRealName = studentRealName == null ? null : studentRealName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.student_num
     *
     * @return the value of message.student_num
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public String getStudentNum() {
        return studentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.student_num
     *
     * @param studentNum the value for message.student_num
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public void setStudentNum(String studentNum) {
        this.studentNum = studentNum == null ? null : studentNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.state
     *
     * @return the value of message.state
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public boolean isState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.state
     *
     * @param state the value for message.state
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public void setState(boolean state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", content=").append(content);
        sb.append(", createTime=").append(createTime);
        sb.append(", studentId=").append(studentId);
        sb.append(", studentRealName=").append(studentRealName);
        sb.append(", studentNum=").append(studentNum);
        sb.append(", state=").append(state);
        sb.append("]");
        return sb.toString();
    }
}