package com.skill.exchange.domain;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.real_uame
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    private String realUame;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_num
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    private String studentNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.password
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.id
     *
     * @return the value of student.id
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.id
     *
     * @param id the value for student.id
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.real_uame
     *
     * @return the value of student.real_uame
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public String getRealUame() {
        return realUame;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.real_uame
     *
     * @param realUame the value for student.real_uame
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public void setRealUame(String realUame) {
        this.realUame = realUame == null ? null : realUame.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_num
     *
     * @return the value of student.student_num
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public String getStudentNum() {
        return studentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_num
     *
     * @param studentNum the value for student.student_num
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public void setStudentNum(String studentNum) {
        this.studentNum = studentNum == null ? null : studentNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.password
     *
     * @return the value of student.password
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.password
     *
     * @param password the value for student.password
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", realUame=").append(realUame);
        sb.append(", studentNum=").append(studentNum);
        sb.append(", password=").append(password);
        sb.append("]");
        return sb.toString();
    }
}