package com.skill.exchange.domain;

import java.util.Date;

public class Trade {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade.id
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade.from_student_id
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    private Integer fromStudentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade.from_student_real_name
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    private String fromStudentRealName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade.from_student_num
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    private String fromStudentNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade.from_skill_id
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    private Integer fromSkillId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade.from_skill_title
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    private String fromSkillTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade.to_student_id
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    private Integer toStudentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade.to_student_real_name
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    private String toStudentRealName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade.to_student_num
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    private String toStudentNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade.to_skill_id
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    private Integer toSkillId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade.to_skill_title
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    private String toSkillTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade.create_time
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade.state
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade.id
     *
     * @return the value of trade.id
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade.id
     *
     * @param id the value for trade.id
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade.from_student_id
     *
     * @return the value of trade.from_student_id
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public Integer getFromStudentId() {
        return fromStudentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade.from_student_id
     *
     * @param fromStudentId the value for trade.from_student_id
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public void setFromStudentId(Integer fromStudentId) {
        this.fromStudentId = fromStudentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade.from_student_real_name
     *
     * @return the value of trade.from_student_real_name
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public String getFromStudentRealName() {
        return fromStudentRealName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade.from_student_real_name
     *
     * @param fromStudentRealName the value for trade.from_student_real_name
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public void setFromStudentRealName(String fromStudentRealName) {
        this.fromStudentRealName = fromStudentRealName == null ? null : fromStudentRealName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade.from_student_num
     *
     * @return the value of trade.from_student_num
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public String getFromStudentNum() {
        return fromStudentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade.from_student_num
     *
     * @param fromStudentNum the value for trade.from_student_num
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public void setFromStudentNum(String fromStudentNum) {
        this.fromStudentNum = fromStudentNum == null ? null : fromStudentNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade.from_skill_id
     *
     * @return the value of trade.from_skill_id
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public Integer getFromSkillId() {
        return fromSkillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade.from_skill_id
     *
     * @param fromSkillId the value for trade.from_skill_id
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public void setFromSkillId(Integer fromSkillId) {
        this.fromSkillId = fromSkillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade.from_skill_title
     *
     * @return the value of trade.from_skill_title
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public String getFromSkillTitle() {
        return fromSkillTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade.from_skill_title
     *
     * @param fromSkillTitle the value for trade.from_skill_title
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public void setFromSkillTitle(String fromSkillTitle) {
        this.fromSkillTitle = fromSkillTitle == null ? null : fromSkillTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade.to_student_id
     *
     * @return the value of trade.to_student_id
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public Integer getToStudentId() {
        return toStudentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade.to_student_id
     *
     * @param toStudentId the value for trade.to_student_id
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public void setToStudentId(Integer toStudentId) {
        this.toStudentId = toStudentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade.to_student_real_name
     *
     * @return the value of trade.to_student_real_name
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public String getToStudentRealName() {
        return toStudentRealName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade.to_student_real_name
     *
     * @param toStudentRealName the value for trade.to_student_real_name
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public void setToStudentRealName(String toStudentRealName) {
        this.toStudentRealName = toStudentRealName == null ? null : toStudentRealName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade.to_student_num
     *
     * @return the value of trade.to_student_num
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public String getToStudentNum() {
        return toStudentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade.to_student_num
     *
     * @param toStudentNum the value for trade.to_student_num
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public void setToStudentNum(String toStudentNum) {
        this.toStudentNum = toStudentNum == null ? null : toStudentNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade.to_skill_id
     *
     * @return the value of trade.to_skill_id
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public Integer getToSkillId() {
        return toSkillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade.to_skill_id
     *
     * @param toSkillId the value for trade.to_skill_id
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public void setToSkillId(Integer toSkillId) {
        this.toSkillId = toSkillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade.to_skill_title
     *
     * @return the value of trade.to_skill_title
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public String getToSkillTitle() {
        return toSkillTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade.to_skill_title
     *
     * @param toSkillTitle the value for trade.to_skill_title
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public void setToSkillTitle(String toSkillTitle) {
        this.toSkillTitle = toSkillTitle == null ? null : toSkillTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade.create_time
     *
     * @return the value of trade.create_time
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade.create_time
     *
     * @param createTime the value for trade.create_time
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade.state
     *
     * @return the value of trade.state
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade.state
     *
     * @param state the value for trade.state
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade
     *
     * @mbg.generated Fri Apr 19 11:32:55 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", fromStudentId=").append(fromStudentId);
        sb.append(", fromStudentRealName=").append(fromStudentRealName);
        sb.append(", fromStudentNum=").append(fromStudentNum);
        sb.append(", fromSkillId=").append(fromSkillId);
        sb.append(", fromSkillTitle=").append(fromSkillTitle);
        sb.append(", toStudentId=").append(toStudentId);
        sb.append(", toStudentRealName=").append(toStudentRealName);
        sb.append(", toStudentNum=").append(toStudentNum);
        sb.append(", toSkillId=").append(toSkillId);
        sb.append(", toSkillTitle=").append(toSkillTitle);
        sb.append(", createTime=").append(createTime);
        sb.append(", state=").append(state);
        sb.append("]");
        return sb.toString();
    }
}